Repository surveysparrow/twigs, pull requests merged in 2024-08, with the labels that each got.

#70 table component ui improvement
  packages/docs/docs/components/table.mdx
  packages/docs/src/theme/ReactLiveScope/index.js
  packages/docs/static/doc-snippets/table.mdx
  packages/react-components/src/table/table.tsx
Labels: enhancement

#108 Releases 23 july 2024
  packages/docs/docs/components/editor/features/link.mdx
  packages/docs/docs/components/table.mdx
  packages/docs/src/theme/ReactLiveScope/index.js
  packages/docs/static/doc-snippets/editor-feature-convert-pasted-text-to-link.mdx
  packages/docs/static/doc-snippets/table.mdx
  packages/react-components/package.json
  packages/react-components/rollup.config.base.js
  packages/react-components/src/editor/components/dialog-link-editor/link-editor-dialog.tsx
  packages/react-components/src/editor/components/toolbar/tools/link.tsx
  packages/react-components/src/editor/editor.tsx
  packages/react-components/src/editor/plugins/hashtag/index.tsx
  packages/react-components/src/editor/plugins/link/convert-selection-on-paste.tsx
  packages/react-components/src/editor/plugins/link/index.tsx
  packages/react-components/src/editor/plugins/mentions/index.tsx
  packages/react-components/src/editor/utils/use-node-focus.ts
  packages/react-components/src/table/table.tsx
  packages/react-components/src/theme-provider/theme-provider.tsx
Labels: bug, documentation, enhancement

#116 Releases 08 aug 2024
  packages/docs/docs/components/datepicker.mdx
  packages/react-components/package.json
  packages/react-components/src/datepicker/datepicker.tsx
  packages/react-components/src/dropdown/dropdown.tsx
Labels: documentation, enhancement

#124 Releases 19 aug 2024
  packages/docs/docs/components/calendar-range.mdx
  packages/docs/docs/components/calendar.mdx
  packages/docs/docs/components/datepicker.mdx
  packages/docs/docs/components/editor/features/emoji.mdx
  packages/docs/src/components/theming/font-sizes.tsx
  packages/docs/src/theme/ReactLiveScope/index.js
  packages/docs/static/doc-snippets/editor-feature-emoji.mdx
  packages/react-components/jest.config.json
  packages/react-components/package.json
  packages/react-components/src/calendar/calendar-cell.tsx
  packages/react-components/src/calendar/calendar-grid.tsx
  packages/react-components/src/calendar/calendar-months-view.tsx
  packages/react-components/src/calendar/calendar-range.tsx
  packages/react-components/src/calendar/calendar-utils.ts
  packages/react-components/src/calendar/calendar-years-view.tsx
  packages/react-components/src/calendar/calendar.tsx
  packages/react-components/src/datepicker/datepicker.tsx
  packages/react-components/src/editor/nodes/emoji.ts
  packages/react-components/src/editor/nodes/index.ts
  packages/react-components/src/editor/plugins/emoji/emoji-list.ts
  packages/react-components/src/editor/plugins/emoji/index.tsx
  packages/react-components/src/editor/plugins/index.tsx
  packages/react-components/src/toast/toastr.tsx
Labels: bug, documentation, enhancement

#129 Releases 23 aug 2024
  packages/docs/docs/components/table.mdx
  packages/docs/static/doc-snippets/table.mdx
  packages/react-components/package.json
  packages/react-components/src/table/stories/table.stories.tsx
  packages/react-components/src/table/table.tsx
Labels: documentation, enhancement
