Repository surveysparrow/twigs, pull requests merged in 2024-06, with the labels that each got.

#79 Editor UI updates and bug fixes
  packages/react-components/src/editor/components/dialog-link-editor/index.tsx
  packages/react-components/src/editor/components/dialog-link-editor/link-editor-dialog.tsx
  packages/react-components/src/editor/components/dialog-link-editor/link-tooltip.tsx
  packages/react-components/src/editor/components/rich-editor/index.tsx
  packages/react-components/src/editor/components/toolbar/tools/commons.ts
  packages/react-components/src/editor/components/toolbar/tools/link.tsx
  packages/react-components/src/editor/components/toolbar/tools/ordered-list.tsx
  packages/react-components/src/editor/components/toolbar/tools/unordered-list.tsx
  packages/react-components/src/editor/plugins/hashtag/index.tsx
  packages/react-components/src/editor/plugins/mentions/index.tsx
Labels: bug, enhancement

#80 Releases - 10 jun 2024
  packages/react-components/package.json
  packages/react-components/src/editor/components/dialog-link-editor/index.tsx
  packages/react-components/src/editor/components/dialog-link-editor/link-editor-dialog.tsx
  packages/react-components/src/editor/components/dialog-link-editor/link-tooltip.tsx
  packages/react-components/src/editor/components/rich-editor/index.tsx
  packages/react-components/src/editor/components/toolbar/tools/commons.ts
  packages/react-components/src/editor/components/toolbar/tools/link.tsx
  packages/react-components/src/editor/components/toolbar/tools/ordered-list.tsx
  packages/react-components/src/editor/components/toolbar/tools/unordered-list.tsx
  packages/react-components/src/editor/plugins/hashtag/index.tsx
  packages/react-components/src/editor/plugins/mentions/index.tsx
Labels: bug, documentation, enhancement

#82 Releases 13 jun 2024
  packages/react-components/package.json
  packages/react-components/src/calendar/calendar-cell.tsx
  packages/react-components/src/calendar/calendar-commons.tsx
  packages/react-components/src/calendar/calendar-day.tsx
  packages/react-components/src/calendar/calendar-grid.tsx
  packages/react-components/src/calendar/calendar-header.tsx
  packages/react-components/src/calendar/calendar-months-view.tsx
  packages/react-components/src/calendar/calendar-range.tsx
  packages/react-components/src/calendar/calendar-time-picker.tsx
  packages/react-components/src/calendar/calendar-timezone-picker.tsx
  packages/react-components/src/calendar/calendar-utils.ts
  packages/react-components/src/calendar/calendar-week.tsx
  packages/react-components/src/calendar/calendar-years-view.tsx
  packages/react-components/src/calendar/calendar.tsx
  packages/react-components/src/datepicker/datepicker.tsx
  packages/react-components/src/datepicker/stories/datepicker.stories.tsx
  packages/react-components/src/hooks/use-previous.ts
  yarn.lock
Labels: documentation, enhancement

#77 Text component design fixes
  packages/docs/docs/components/heading.mdx
  packages/react-components/src/heading/heading.tsx
  packages/react-components/src/text/text.tsx
Labels: documentation

#76 docs sidebar improvement
  packages/docs/docs/components/_category_.json
  packages/docs/docs/components/editor/_category_.json
  packages/docs/docs/components/editor/features/hashtags.mdx
  packages/docs/docs/components/editor/features/index.mdx
  packages/docs/docs/components/editor/features/link.mdx
  packages/docs/docs/components/editor/features/mentions.mdx
  packages/docs/docs/components/editor/helpers/_category_.json
  packages/docs/docs/components/editor/helpers/base-dropdown.mdx
  packages/docs/docs/components/editor/setup.mdx
  packages/docs/docs/components/editor/toolbar.mdx
  packages/docs/docs/components/editor/tutorials/_category_.json
  packages/docs/docs/components/editor/tutorials/slash-command-feature.mdx
  packages/docs/docs/examples/_category_.json
  packages/docs/docs/frameworks-usage/_category_.json
  packages/docs/docs/getting-started.md
  packages/docs/docs/icons.mdx
  packages/docs/src/css/custom.css
Labels: documentation

#83 Releases/24 jun 2024
  packages/docs/docs/components/_category_.json
  packages/docs/docs/components/editor/_category_.json
  packages/docs/docs/components/editor/features/hashtags.mdx
  packages/docs/docs/components/editor/features/index.mdx
  packages/docs/docs/components/editor/features/link.mdx
  packages/docs/docs/components/editor/features/mentions.mdx
  packages/docs/docs/components/editor/helpers/_category_.json
  packages/docs/docs/components/editor/helpers/base-dropdown.mdx
  packages/docs/docs/components/editor/setup.mdx
  packages/docs/docs/components/editor/toolbar.mdx
  packages/docs/docs/components/editor/tutorials/_category_.json
  packages/docs/docs/components/editor/tutorials/slash-command-feature.mdx
  packages/docs/docs/components/heading.mdx
  packages/docs/docs/components/stack.mdx
  packages/docs/docs/examples/_category_.json
  packages/docs/docs/frameworks-usage/_category_.json
  packages/docs/docs/getting-started.md
  packages/docs/docs/icons.mdx
  packages/docs/src/css/custom.css
  packages/docs/src/theme/ReactLiveScope/index.js
  packages/react-components/package.json
  packages/react-components/src/button/button.tsx
  packages/react-components/src/button/index.tsx
  packages/react-components/src/button/split-button-context.ts
  packages/react-components/src/button/split-button.tsx
  packages/react-components/src/button/stories/split-button.stories.tsx
  packages/react-components/src/heading/heading.tsx
  packages/react-components/src/index.ts
  packages/react-components/src/separator/index.tsx
  packages/react-components/src/separator/separator.tsx
  packages/react-components/src/separator/stories/separator.stories.tsx
  packages/react-components/src/separator/tests/index.test.tsx
  packages/react-components/src/stack/get-separator-style.ts
  packages/react-components/src/stack/h-stack.tsx
  packages/react-components/src/stack/index.tsx
  packages/react-components/src/stack/stack.tsx
  packages/react-components/src/stack/stories/stack.stories.tsx
  packages/react-components/src/stack/tests/index.test.tsx
  packages/react-components/src/stack/v-stack.tsx
  packages/react-components/src/stitches.config.ts
  packages/react-components/src/text/text.tsx
  packages/react-components/src/toast/toast.tsx
Labels: documentation, enhancement
